/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "../../lib/utils";
import SideNavbar from "@/components/SideNavbar";
import Topbar from "@/components/Topbar";
import styles from "./index.module.scss"
import localFont from 'next/font/local'

const myFont = localFont({
  src: '../../public/fonts/AppleSDGothicNeoSB.ttf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "강소기업개발진흥원",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-full bg-white text-black flex ",
          myFont.className,
          {
            "debug-screens": process.env.NODE_ENV === "development"
          }
        )}
      >
        {/* sidebar */}
        
        <SideNavbar />
        {/* main page */}
        
        <div className="w-full ">
        <Topbar/>
        <div className={styles.main}>
        {children}
        </div>
        </div>
      </body>
    </html>
  );
}
